from typing import Protocol, runtime_checkable


@runtime_checkable
class GitAdapter(Protocol):
    def create_bare_repo(self, repos_dir: str, username: str, repo_name: str) -> bool: ...
    def get_branches(self, repo_path: str) -> list: ...
    def is_repo_empty(self, repo_path: str) -> bool: ...
    def get_repo_commits(self, repo_path: str, limit: int, branch: str) -> list: ...
    def parse_diff(self, diff_text: str) -> list: ...
    def get_commit_details(self, repo_path: str, commit_hash: str) -> dict: ...
    def get_repo_files(self, repo_path: str, branch: str) -> list: ...
    def get_file_content(self, repo_path: str, filepath: str, branch: str) -> str: ...
    def get_contributors(self, repo_path: str) -> list: ...
    def get_branch_diff(self, repo_path: str, target_branch: str, source_branch: str) -> list: ...
    def get_commit_graph(self, repo_path: str, branch: str, limit: int) -> list: ...
    def get_branch_tips(self, repo_path: str) -> dict: ...
    def merge_branches(self, repo_path: str, target_branch: str, source_branch: str, author_name: str, author_email: str) -> bool: ...
